const STARTLOADING = "STARTLOADING";
const ENDLOADING = "ENDLOADING";


const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const FETCH_ALL = 'FETCH_ALL';
const LIKE = 'LIKE';


const FAIL = 'FAIL';

const AUTH = "AUTH";
const LOGOUT = "LOGOUT";

const SIGNUP = "SIGNUP" ;
const SIGNIN = "SIGNIN" ;

const SEARCHEDPOSTS = "SEARCHEDPOSTS";

const SINGLEFETCH = "SINGLEFETCH";

const COMMENT = "COMMENT";




export {CREATE, UPDATE, DELETE, LIKE, FETCH_ALL, FAIL, AUTH, LOGOUT, SIGNUP, SIGNIN, SEARCHEDPOSTS, STARTLOADING, ENDLOADING, SINGLEFETCH, COMMENT}